JaxGaussianProcesses/GPJax

gpjax/predict.py
Hi! 
First of all, I really like your library! It has a nice and well decoupled code structure.
On to the pull request:
I noticed that the mean function (evaluated at the test inputs) is not added to the output of the predictive mean function of the conjugate posterior, which I reckon is a bug. 
Are you happy with the following fix?
=> Added missing prior mean at test inputs

docs/nbs/barycentres.pct.py, docs/nbs/classification.pct.py, docs/nbs/graph_kernels.pct.py, docs/nbs/haiku.pct.py, docs/nbs/kernels.pct.py, docs/nbs/regression.pct.py, docs/nbs/sparse_regression.pct.py, gpjax/__init__.py, gpjax/abstractions.py, tests/test_abstractions.py
Revise abstraction's `fit` to only support optax optimisers. 
This update involved:
- Removing the at present function `fit` from abstractions
- Renaming `optax_fit` to `fit` to act as the new function that only supports optax
- Revising documentation notebooks to accommodate the new `fit` function & fix minor typos
=> Revise fit in abstractions & minor documentation update.

gpjax/gps.py, gpjax/sparse_gps.py
- Fixed issue #58 to allow nonconjugate posteriors to work with non-zero mean functions.
- Removed `mean` method from GP `Prior` -> this was redundant.
=> Fix Non-conjugate posterior + remove mean from GP prior.

gpjax/types.py, tests/test_types.py
Use `__add__` method on `Dataset` object to facilitate combining two datasets (useful for optimal design purposes).
Example:
```python
import jax.numpy as jnp
import gpjax as gpx
x1 = jnp.array([[1., 2.], [3., 4.])
y1 = jnp.array([[2.], [5.]])
D1 = gpx.Dataset(X=x1, y=y1)
x2 = jnp.array([[7., 11.], [1., 3.], [5., 5.]])
y2 = jnp.array([[8.], [3.], [7.]])
D2 = gpx.Dataset(X=x2, y=y2)
D_combined = D1 + D2
```
- [ X] Feature
=> Add method to combine datasets.

gpjax/gps.py, tests/test_abstractions.py, tests/test_gp.py
Thanks @krunolp for raising this issue.
Conjugate regression contains a bug that arises when calculating the marginal log-likelihood on a single data point. In particular, fitting a GP using only single input-output pair [both with shape (1,1)] results in the following error:
```
bijector BlockShift has event_ndims_out==1, but the input has only 0 array dimensions. 
```
This PR fixes this bug and updates the tests for this edge-case. 
- [X ] Bugfix
=> Fix conjugate regression bug for a single datapoint.

gpjax/config.py, gpjax/parameters.py, setup.py, tests/test_parameters.py
This PR relaxes the strict Jax requirement present in previous version of GPJax. This should resolve #102
- [ x ] Bugfix
Right now we cannot use Jax versions beyond 0.3.5. By extending the distrax bijectors and updating some Jax tree-based operations, we can simply make this versioning an inequality to install the latest Jax version.
Issue Number: #102
=> Relax Jax version

examples/barycentres.ipynb, examples/classification.ipynb, examples/collapsed_vi.ipynb, examples/graph_kernels.ipynb, examples/haiku.ipynb, examples/kernels.ipynb, examples/regression.ipynb, examples/tfp_integration.ipynb, examples/uncollapsed_vi.ipynb, examples/yacht.ipynb, gpjax/__init__.py, gpjax/abstractions.py, gpjax/gps.py, gpjax/parameters.py, gpjax/variational_inference.py, tests/test_abstractions.py, tests/test_gp.py, tests/test_kernels.py, tests/test_likelihoods.py, tests/test_mean_functions.py, tests/test_parameters.py, tests/test_variational_inference.py
The PR refactors transformations #105.
Transformations have been removed from objective functions e.g. the marginal likelihood. So instead of e.g., `objective = posterior.mll(D, transformation, negative=True)`, we now do `objective = posterior.mll(D, negative=True)`. The transformations are instead placed with training loops.
To remove clutter, we remove the dictionary `constrainers` and `unconstrainers` notion, and instead define transformations via bijectors. In particular:
- The `ParameterState` dataclass now comprises `params`,` trainables `and `bijectors`. So e.g. calling `parameter_state = gpx.initialise(posterior, key)`and then `parameter_state.unpack()` returns a tuple `params, trainables, bijectors`.
- The function `gpx.transform` has been removed. To transform parameters to the …
=> Transformations

gpjax/abstractions.py, tests/test_abstractions.py
Simple implementation of verbosity option #115 . 
Tests don't check if this works or not, but only if any error occurs when turning verbosity on/off.
Training loops tests have been updated to ensure testing of edge case of a single iteration.
=> Add verbose option.

examples/barycentres.pct.py, examples/classification.pct.py, examples/collapsed_vi.pct.py, examples/graph_kernels.pct.py, examples/haiku.pct.py, examples/kernels.pct.py, examples/natgrads.pct.py, examples/regression.pct.py, examples/tfp_integration.pct.py, examples/uncollapsed_vi.pct.py, examples/yacht.pct.py, gpjax/__init__.py, tests/test_abstractions.py, tests/test_config.py, tests/test_covariance_operator.py, tests/test_gps.py, tests/test_kernels.py, tests/test_likelihoods.py, tests/test_mean_functions.py, tests/test_natural_gradients.py, tests/test_parameters.py, tests/test_quadrature.py, tests/test_types.py, tests/test_utilities.py, tests/test_variational_families.py, tests/test_variational_inference.py
Make float32 the default type, not f64.
- [ x ] Refactoring (no functional changes, no api changes)
Currently we enforce float 64. However, despite giving more stable matrix inversions, this limits reproducibility. 
Issue Number: #128 
Default to float32 and set float64 in notebooks.
-
-
-
=> Prevent f64 default

docs/conf.py, docs/contributing.md, docs/requirements.txt, examples/tfp_integration.pct.py, gpjax/config.py
=> Update w/ Dan comments

gpjax/abstractions.py, gpjax/config.py, gpjax/gps.py, gpjax/kernels.py, gpjax/mean_functions.py, gpjax/variational_families.py, gpjax/variational_inference.py
Minor addition of comments and code readability improvements [e.g., replacing long attributes such as `self.prior.kernel(...)` with `kernel = self.prior.kernel` then `kernel(...)`]. Most major changes are to the progress bar.
- [X ] Code style update (formatting, renaming)
=> Improve readability and add comments.

README.md, examples/barycentres.pct.py, examples/classification.pct.py, examples/collapsed_vi.pct.py, examples/graph_kernels.pct.py, examples/haiku.pct.py, examples/kernels.pct.py, examples/natgrads.pct.py, examples/regression.pct.py, examples/tfp_integration.pct.py, examples/uncollapsed_vi.pct.py, examples/yacht.pct.py, gpjax/gps.py, gpjax/kernels.py, gpjax/likelihoods.py, gpjax/mean_functions.py, gpjax/variational_families.py, gpjax/variational_inference.py, tests/test_gps.py, tests/test_kernels.py, tests/test_likelihoods.py, tests/test_mean_functions.py, tests/test_variational_families.py
This PR moves the `params` argument to the first slot of each function, to match the convention of `Haiku` and `Flax`.
Also, cleans up some of the tests, add typing, for readability and adds testing of abstract classes. Some test files e.g. 'test_gps.py` need cleaning up, in future.
- [ X] Code style update (formatting, renaming)
=> Move params to the first slot of each function, class, etc.

gpjax/abstractions.py, gpjax/gaussian_distribution.py, gpjax/gps.py, gpjax/kernels.py, gpjax/likelihoods.py, gpjax/mean_functions.py, gpjax/natural_gradients.py, gpjax/variational_families.py, gpjax/variational_inference.py
fixes a couple of typos around comments and docstrings
=> typo fixes

examples/classification.pct.py, examples/collapsed_vi.pct.py, examples/haiku.pct.py, examples/natgrads.pct.py, examples/regression.pct.py, examples/tfp_integration.pct.py, examples/uncollapsed_vi.pct.py
In some of the examples, the same PRNGKey is used to generate both x and the noise in y, and x is sorted to avoid the correlation resulting by using the same key. This could be somewhat confusing for new users (myself included).
We simply split the key and use two separate keys to generate x and the noise in y.
=> Correct key handling in examples

gpjax/kernels/stationary/matern12.py, gpjax/kernels/stationary/matern32.py, gpjax/kernels/stationary/matern52.py, gpjax/kernels/stationary/periodic.py, gpjax/kernels/stationary/powered_exponential.py, gpjax/kernels/stationary/rational_quadratic.py, gpjax/kernels/stationary/rbf.py, gpjax/kernels/stationary/utils.py, gpjax/kernels/stationary/white.py, gpjax/parameters/module.py, tests/test_kernels/test_stationary.py
=> Refactoring kernels

examples/regression.pct.py, examples/yacht.pct.py, gpjax/gps.py, gpjax/mean_functions.py, gpjax/types.py, tests/test_gps.py, tests/test_parameters.py
I have added a method to the GP prior so that we can get approximate samples from the GP.  I use the standard RFF approach to get samples with functional forms that can be cheaply queried as many times as we like.
=> Rff sampler

.pre-commit-config.yaml, docs/conf.py, docs/conf_sphinx_patch.py, gpjax/__init__.py, gpjax/gps.py, tests/test_gps.py, tests/test_likelihoods.py
Based on potential worry from @frazane, I have changed the unit tests to be for a 2d dataset with ARD (i.e. different lengthscales). 
I also fixed a small bug that was added when changing the backend (@thomaspinder ;)) which meant that we never controlled the seed that set the random fourier features. Previously, I was using a `.init_params` but this wasn't updated properly.
While I was at it, I also tidied my code slightly to reuse RFF functionality between the prior and posterior samplers.
There was a bit of extra formatting fixing that went on as well. Not sure why???
=> Tidy up RFF and extra tests/formatting

.github/workflows/tests.yml, examples/deep_kernels.pct.py, examples/kernels.pct.py, gpjax/base/__init__.py, gpjax/base/module.py, gpjax/base/param.py, gpjax/gps.py, gpjax/kernels/approximations/rff.py, gpjax/kernels/base.py, gpjax/kernels/non_euclidean/graph.py, gpjax/kernels/nonstationary/arccosine.py, gpjax/kernels/nonstationary/polynomial.py, gpjax/kernels/stationary/white.py, gpjax/likelihoods.py, gpjax/linops/constant_diagonal_linear_operator.py, gpjax/mean_functions.py, gpjax/objectives.py, gpjax/variational_families.py, tests/test_base/test_module.py, tests/test_kernels/test_base.py, tests/test_linops/test_linear_operator.py
This PR comprises the following changes:
- (1) Add `static_field` to base, and use this in the testing.
- (2) Limit `simple_pytree` imports to 3 places (and the tests only):
- (a)`gpjax.base`
- (b)`gpjax.linops.linear_operator` (We should update this to a module in future).
- (c)`gpjax.dataset` (We should update this to a module in future).
There should be no other imports. 
- Will need to remove `simple_pytree` imports from the `docs_update` branch in a separate PR.
- Perhaps ought to consider (in a future PR), only using `Module` and limiting `simple_pytree` import to `gpjax.base`.
This PR  also fixes compatibility issues with Python 3.11, that requires dataclass fields to be hashable (while jax.Arrays are not...).
=> Add static field to base, update tests to run on 3.11, fix 3.11 compatibility

docs/contributing.md, docs/scripts/notebook_converter.py, mkdocs.yml
This PR extracts the code from each notebooks we've written, concatenates it, and writes it to a markdown file. This gives a "give me the code" style page where users can easily copy and past the notebooks code into their Python work.
- [-] I've added tests for new code.
- [-] I've added docstrings for the new code.
=> Autogen code

tests/test_kernels/test_stationary.py
In GPJax versions <0.6, we have a bug that prevented users defining an isotropic kernel when their data was greater than a single dimension. This issue was inadvertently fixed in the v0.6 release. This PR simply adds a test to make sure an isotropic kernel can be specified.
Issue Number: #237
=> Add isotropy test

gpjax/kernels/stationary/powered_exponential.py, mkdocs.yml, tests/test_kernels/test_stationary.py
Based on the equivalence of this kernel with symmetric generalized gaussian densities (up to a difference in the power parametrization) and according to https://en.wikipedia.org/wiki/Generalized_normal_distribution#Connection_to_Positive-Definite_Functions the power parameter has to be in the interval (0, 1] for the kernel to be positive semidefinite. Adding a Sigmoid constraint to enforce that.
=> Bugfix powered_exponential.py

gpjax/fit.py, gpjax/gps.py, gpjax/likelihoods.py, tests/test_gps.py
I added two small improvements to the static typing which will make coding with GPJax a bit easier, especially in fully featured IDEs.
- `construct_posterior` and `__mul__` are overloaded such that the correct posterior (abstract, conjugate or nonconjugate) is returned when we construct the posterior (current behavior is that an `AbstractPosterior` is always returned). This way we get proper tab-completion and information (signatures, docstrings) when mouse-hovering on an object. 
- pass (and return) a `TypeVar` (with `Module` as the upper bound) in `fit` instead of `Module` itself, such that we retain the right static typing information about the model we are using
=> Static typing fixes

docs/examples/likelihoods_guide.py, docs/examples/yacht.py, gpjax/__init__.py, mkdocs.yml
- [-] I've added tests for new code.
- [-] I've added docstrings for the new code.
This PR introduces a piece of documentation that provides users with a guide to likelihood functions and how the integration strategy attached to a likelihood function can be changed.
Issue Number: #295 #294
=> Add integrator/likelihoods doc

docs/examples/uncollapsed_vi.py
Current `uncollapsed_vi.py` notebook gives me `nan`s when I run it locally with the scheduler peaked at 0.1. I have changed the `peak_value=0.01` to avoid the issue. Optimisation works as expected after that.
=> changed schedule peak_value to 1e-2 for the svgp notebook so it does not give nans

gpjax/kernels/computations/basis_functions.py
The scaling was only applied to one of the arguments here:
https://github.com/JaxGaussianProcesses/GPJax/blob/549270f0f088da6eeede2182c6b2528b2a5275d0/gpjax/kernels/computations/basis_functions.py#L31-L34
but should be applied outside the matrix computation. This PR fixes this. 
=> Bugfix in BasisFunctionComputation

README.md, docs/contributing.md, docs/examples/intro_to_gps.py, docs/examples/pytrees.md
Updated documentation for contributing to reflect the change to using Poetry for dependency management. Also added the command for manually running the pre-commit hook to the documentation.
Also fixed a few broken links and typos I had encountered.
Poetry is now used for dependency management, but the documentation for contributing hadn't been updated to reflect this. Therefore, the documentation for contributing has been updated to reflect this change. A few broken links and typos have also been fixed.
=> Update contribution documentation

docs/examples/constructing_new_kernels.py
Polar GP example was non-continuous through 0 - 2\pi. When defining the half-period constant c as follows:
```
period: float = static_field(2 * jnp.pi)
tau: float = param_field(jnp.array([4.0]), bijector=bij)
def __post_init__(self):
self.c = self.period / 2.0
```
`c` was still training as a parameter during optimisation and wasn't being considered static, resulting in an invalid Polar GP (I believe). Therefore I moved the definition of `c` to within the __call__ method of the kernel, maintaining it as a constant during hyper-parameter optimisation. I'm not 100% sure on why this behaviour is happening, with training a constant, but this fixes it. 
I have changed the docs to reflect this, also …
=> Fixed Polar GP example

gpjax/dataset.py, tests/test_dataset.py
Have added a warning using the ```warnings``` package that informs when X or y isn't of dtype float64 (if the warnings package isn't appropriate then please let me know, it's a new import within ```dataset.py```). This is called immediately after checking the dataset shape:
```
def __post_init__(self) -> None:
r"""Checks that the shapes of $`X`$ and $`y`$ are compatible,
and provides warnings regarding the precision of $`X`$ and $`y`$."""
_check_shape(self.X, self.y)
-->>  _check_precision(self.X, self.y)
```
I've added a test for the warning generation, but to do so I had to enable the higher precision within ```test_dataset.py``` (```config.update("jax_enable_x64", True)```) .  I hope this solution is alright. Thanks!
Issue Number: #342
=> Precision check feature

tests/test_objectives.py
Set 64 bit precision in objectives tests due to change in https://github.com/JaxGaussianProcesses/GPJax/pull/347 causing tests to fail when run in isolation.
- [N/A] I've added tests for new code.
- [N/A] I've added docstrings for the new code.
Objectives tests were failing when run in isolation due to https://github.com/JaxGaussianProcesses/GPJax/pull/347. However, when all tests where run together they would pass (presumably due to 64 bit precision being set by an earlier set of tests). Therefore, 64 bit precision has been added to the objectives tests so that they can be run successfully in isolation.
=> Fix objectives tests

gpjax/bayes_opt/__init__.py, gpjax/bayes_opt/search_space.py, gpjax/kernels/__init__.py, gpjax/kernels/non_euclidean/categorical.py, tests/test_bayes_opt/test_search_space.py, tests/test_dataset.py, tests/test_kernels/test_non_euclidean.py
Added an `AbstractSearchSpace` abstract base class for the BayesOpt library, as well as a concrete implementation in the form of a `ContinuousSearchSpace` class. Tests have also been added.
Starting to add fully tested Bayesian Optimisation functionality. This first PR adds a class for defining (and sampling from) search spaces, over which optimisation is performed.
=> Add search space class for BayesOpt

gpjax/dataset.py, gpjax/fit.py, gpjax/gaussian_distribution.py, gpjax/gps.py, gpjax/linops/dense_linear_operator.py, gpjax/objectives.py, tests/test_dataset.py, tests/test_gaussian_distribution.py
This PR introduces support for missing data points (missing `y`s) in a way that is compatible with JAX jit-compilation (by keeping shapes static). This could be particularly useful in meta-learning settings (where each task has a variable number of available training points), or in multi-output GPs where only some of the outputs are missing (@ingmarschuster).
- new attribute `mask` added to the `Dataset`object
- added code to computations of `log_prob` and to posterior predictions, such that masked training inputs have no influence on the results
For now I only tested this on a simple exact GP with gaussian likelihood.
=> Support for missing values using masked dataset

docs/examples/decision_making.py, gpjax/decision_making/__init__.py, gpjax/decision_making/decision_maker.py, gpjax/decision_making/utility_functions/__init__.py, gpjax/decision_making/utility_functions/base.py, gpjax/decision_making/utility_functions/thompson_sampling.py, gpjax/decision_making/utility_maximizer.py, mkdocs.yml, tests/test_decision_making/test_decision_maker.py, tests/test_decision_making/test_utility_maximizer.py, tests/test_decision_making/utils.py
In the future certain utility functions will be "batched" utility functions which quantify the utility of querying a *batch* of points rather than a single point. These utility functions may in turn be optimised differently.
Therefore, I propose we have a `SinglePointUtilityFunction` type for non-batched utility functions, which has type annotation `[N  D] -> [N 1]`, and in the future we may add `BatchUtilityFunction` which has type  annotation `[N B D] -> [N 1]`. Distinguishing between these makes it easy for users to see which utility functions support batching.
Also refactored UtilityDrivenDecisionMaker to enable for Thompson sampling to be used in a batched context, and updated unit tests to reflect this. Finally, added a new notebook to serve as an introduction to the …
=> Prepare for future batching

docs/examples/barycentres.py, docs/examples/bayesian_optimisation.py, docs/examples/classification.py, docs/examples/collapsed_vi.py, docs/examples/constructing_new_kernels.py, docs/examples/deep_kernels.py, docs/examples/graph_kernels.py, docs/examples/intro_to_kernels.py, docs/examples/likelihoods_guide.py, docs/examples/oceanmodelling.py, docs/examples/poisson.py, docs/examples/regression.py, docs/examples/regression_mo.py, docs/examples/spatial.py, docs/examples/uncollapsed_vi.py, docs/examples/yacht.py, tests/test_citations.py, tests/test_dataset.py, tests/test_fit.py, tests/test_gaussian_distribution.py, tests/test_gps.py, tests/test_integrators.py, tests/test_kernels/test_approximations.py, tests/test_kernels/test_base.py, tests/test_kernels/test_non_euclidean.py, tests/test_kernels/test_nonstationary.py, tests/test_kernels/test_stationary.py, tests/test_likelihoods.py, tests/test_objectives.py, tests/test_variational_families.py
Updated how we import config from jax. Our current method has been deprecated on the most recent version of jax. The new method works for the older versions and the new versions.
=> fix config import

gpjax/integrators.py, tests/test_integrators.py
- Fixing `AnalyticalGaussianIntegrator` and update tests, as mentioned in #413. 
- Updating the respective docstring to remove a duplicated variance term.
Issue Number: #413
=> Fix AnalyticalGuassianIntegrator

gpjax/base/module.py, tests/test_base/test_module.py
Fix inheritance bug #415 and add a test.
=> Fix bug and add test.

docs/examples/bayesian_optimisation.py
- [N/a] I've added tests for new code.
- [N/a] I've added docstrings for the new code.
Fixed BO notebook. After the zero mean function bug was fixed in PR #358 this affected the fit of the GPs used in the BO notebook. The toy functions have now been standardised to deal with this.
=> Fix BO notebook

docs/examples/intro_to_kernels.py
- Increases the number of data points for the hyperparameter inference example in the intro to kernels notebook -> makes it visually make more sense
- factors out `plot_ribbon` function to simplify notebook (-> should we move this into a plotting_utils or some such? presumably it would be useful for more notebooks)
=> Clean up intro to kernels notebook

docs/examples/intro_to_gps.py
The definition of joint distribution was missing a line of the covariance matrix and the definition of marginalisation was missing the end of a line as well.
=> Minor typos in mathematical definitions in intro_to_gps.py

docs/examples/oceanmodelling.py
Oceanmodelling example notebook wasn't working in python 3.11 or 3.12:
ValueError: mutable default <class 'gpjax.kernels.stationary.rbf.RBF'> for field kernel0 is not allowed: use default_factory
Fixed this issue by replacing direct assignment of kernels with field(default_factory=...). Although checked backwards compatibility with python 3.10
=> Fixed mutable default value error in VelocityKernel and HelmholtzKernel dataclasses in python 3.11

gpjax/base/module.py, gpjax/decision_making/utility_functions/thompson_sampling.py
Fix some incorrect type annotations causing errors when running with the most recent version of beartype (0.18.5).
```
ImportError while loading conftest '/.../GPJax/tests/conftest.py'.
tests/conftest.py:8: in <module>
import gpjax  # noqa: F401
/nix/store/kf64ch0bfisffrcy9w44dd2z3c6b7cq9-python3.11-jaxtyping-0.2.28/lib/python3.11/site-packages/jaxtyping/_import_hook.py:223: in exec_module
return super().exec_module(module)
gpjax/__init__.py:15: in <module>
from gpjax import (
/nix/store/kf64ch0bfisffrcy9w44dd2z3c6b7cq9-python3.11-jaxtyping-0.2.28/lib/python3.11/site-packages/jaxtyping/_import_hook.py:223: in exec_module
return super().exec_module(module)
gpjax/base/__init__.py:16: in <module>
from gpjax.base.module import (
/nix/store/kf64ch0bfisffrcy9w44dd2z3c6b7cq9-python3.11-jaxtyping- …
```
=> Fix some type annotations causing failing tests

gpjax/kernels/base.py, gpjax/kernels/computations/basis_functions.py, tests/test_kernels/test_approximations.py, tests/test_kernels/test_nonstationary.py, tests/test_kernels/test_stationary.py
`AbstractKernel` has wrappers for `cross_covariance` and `gram` but not for `diagonal`, when all three are defined by `AbstractKernelComputation` (`diagonal` is actually concretely implemented by `AbstractKernelComputation`). 
This PR adds `diagonal` to `AbstractKernel`. 
Although the change is trivial, I believe it's important for the following reasons.
Currently, the way to get the diagonal of a kernel matrix efficiently would be code like
```python
import jax.numpy as jnp
from gpjax.kernels import DenseKernelComputation, Matern52
kernel = Matern52()
diagonal = DenseKernelComputation().diagonal
print(diagonal(kernel, jnp.zeros((10, 3))))
```
Other than being needlessly verbose, this obscures the fact that most of the `*Computation` classes (`DiagonalKernelComputation`, etc.) could be …
=> feat(gpjax/kernels/base.py): add diagonal

gpjax/__init__.py, gpjax/gps.py, tests/test_gps.py
- Added an optional solver_algorithm parameter to the `ConjugatePosterior.sample_approx` method for solving the inverse of the covariance matrix.
- Updated the `test_conjugate_posterior_sample_approx` test function to include the `solver_algorithm` parameter.
Issue Number: #475. Related issue https://github.com/JaxGaussianProcesses/GPJax/issues/381.
=> optional solver_algorithm parameter to sample_approx

gpjax/scan.py
- [ x ] I've formatted the new code by running `hatch run dev:format` before committing.
Migrate from `jax.experimental.host_callback()` to `jax.debug.callback()` (see [here](https://github.com/jax-ml/jax/issues/20385)). Fixes #479.
Issue Number: #479
=> Fix callbacks

examples/intro_to_kernels.py, gpjax/likelihoods.py
- [ x  ] I've formatted the new code by running `hatch run dev:format` before committing.
Previously, a `Static` object passed as the `obs_stddev` argument to the `Gaussian` likelihood would be wrapped in `PositiveReal` because `isinstance(Static, Parameter)` evaluates to `False`. This was affecting examples `intro_to_kernels.py` and `bayesian_optimisation.py`. This PR fixes it.
=> Fix `Static` check in `Gaussian` likelihood

gpjax/variational_families.py
- [ x ] I've formatted the new code by running `hatch run dev:format` before committing.
- [ NA  ] I've added tests for new code.
As things stand, `AbstractVariationalGaussian` defaults to static `inducing_inputs` and making them trainable requires manual surgery. This PR enables passing trainable (i.e. `Real`) or fixed (i.e. `Static`) `inducing_inputs` to `AbstractVariationalGaussian`. When an array is passed as `inducing_inputs`, it is wrapped in `Real` by default, to mimic the default behaviour in other GP libraries.
I am happy to write unit tests if required.
=> Allow to pass trainable inducing inputs to AbstractVariationalGaussian

mkdocs.yml
- [ NA ] I've formatted the new code by running `hatch run dev:format` before committing.
Previously, the collapsed and uncollapsed VI examples in the docs were swapped. This PR fixes it.
=> Swap collapsed_vi.md and uncollapsed_vi.md

gpjax/gps.py, gpjax/variational_families.py
- [ x ] I've formatted the new code by running `hatch run dev:format` before committing.
The constructor methods of classes `ExpectationVariationalGaussian`, `NaturalVariationalGaussian`, `NonConjugatePosterior` and `VariationalGaussian` take optional array arguments (e.g. `variational_mean`), which are currently processed with the syntax `array or default_array`. When arrays are passed as arguments, this raises the error `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`. This PR fixes it.
=> Fix optional array arguments in class constructors

README.md, docs/index.md, examples/backend.py, examples/barycentres.py, examples/bayesian_optimisation.py, examples/classification.py, examples/collapsed_vi.py, examples/constructing_new_kernels.py, examples/decision_making.py, examples/deep_kernels.py, examples/graph_kernels.py, examples/intro_to_gps.py, examples/intro_to_kernels.py, examples/likelihoods_guide.py, examples/oceanmodelling.py, examples/poisson.py, examples/regression.py, examples/uncollapsed_vi.py, examples/yacht.py, gpjax/decision_making/test_functions/non_conjugate_functions.py
There are many broken links in the documentation referencing the examples. I have fixed them in this PR.
=> fix: update links in documentation to use the correct path for examples

.github/workflows/tests.yml, examples/intro_to_gps.py, gpjax/__init__.py, pyproject.toml, tests/test_decision_making/test_utility_functions/test_expected_improvement.py, tests/test_fit.py
Fix some failing tests with jax 0.5.1. It seems from 0.5.0 -> 0.5.1 the numerics got slightly worse (especially for inverse).
For the `get_batch` test, as I understand since it's sampling with replacement it's possible to get unlucky and have two rows coincide. This is most likely when the batch size is large (the tests that fail are when the batch size is the same as the dataset size). We'd expect `n_dim * batch_size / n_data` elements to collide (each row has a `1 / n_data` chance of colliding, each collision makes `n_dim` elements the same, and there are `batch_size` rows).
Related to https://github.com/JaxGaussianProcesses/GPJax/issues/490.
=> Fix tests with jax 0.5.1

examples/constructing_new_kernels.py, examples/intro_to_gps.py, examples/intro_to_kernels.py, examples/utils.py, gpjax/distributions.py, tests/test_dataset.py, tests/test_decision_making/test_search_space.py, tests/test_gps.py, tests/test_parameters.py
The diff is large thanks to the automatic ruff fixes when running `hatch run dev:all-tests`; review commit-by-commit. The first commit is a remix of https://github.com/JaxGaussianProcesses/GPJax/pull/437. The second commit is a little suspicious, but the `State`s are small enough for it to be reasonable. A proper solution might implement `__eq__` in `gpjax.parameters.Parameter` to compare value and metadata for variables, but I thought this was overkill for a single test (also I don't know the flax api that well).
Related to https://github.com/JaxGaussianProcesses/GPJax/issues/490, https://github.com/JaxGaussianProcesses/GPJax/pull/497.
=> Fix jaxtyping and flax issues in tests

docs/sharp_bits.md, gpjax/kernels/nonstationary/polynomial.py, gpjax/parameters.py, tests/test_parameters.py
This PR replaces regular assertions with ones from JAX's checkify module. This allows for assertions to be done in a manner which is still JIT-compilable.
Issue Number: #495
=> Add JIT-safe assertions

examples/constructing_new_kernels.py, gpjax/kernels/nonstationary/arccosine.py, gpjax/kernels/nonstationary/linear.py, gpjax/kernels/nonstationary/polynomial.py, gpjax/kernels/stationary/base.py, gpjax/likelihoods.py, gpjax/parameters.py, tests/test_kernels/test_nonstationary.py, tests/test_kernels/test_stationary.py, tests/test_likelihoods.py, tests/test_numpyro_extras.py, tests/test_parameters.py
Introduced a new NonNegativeReal parameter type. This has two primary applications.
This has been implemented into kernel variance parameters. This allows kernels to be 'turned off' as required by setting `variance=gpx.parameter.Static(0.0)`. This is potentially useful for kernel searching algorithms. 
I have been using this feature as an optional add-on kernel which defaults to 'off'.
By allowing `gpx.likelihoods.Gaussian()` to accept `obs_stddev=0.0` we can 'turn off' the likelihood. This is important for GP emulators of computer models. The easiest way to see this working well is by removing the observation noise from the regression example on the documentation.
There is perhaps a cleaner solution by defining a new likelihood class, `emulator` say, with no `obs_stddev` argument which …
=> Introduce NonNegativeReal parameters

gpjax/__init__.py, gpjax/fit.py, tests/test_fit.py, tests/test_mean_functions.py
L-BFGS tends to be the most commonly used optimizer for fitting GPs (used, for example, in GPytorch/Botorch).
`gpx.fit_scipy` under the hood used `scipy.optimize.minimize`, which defaults to running L-BFGS (note, not `jax.scipy` but the original scipy, as `jax.scipy` only has BFGS rather than the reduced memory L-BFGS).
Optax has an [LBFGS implementation](https://optax.readthedocs.io/en/stable/_collections/examples/lbfgs.html#l-bfgs-as-a-solver), but **the API requires some additional arguments, namely `value`, `grad`, and `value_fn` in the `optim.update` step, that means that it can't be directly with `gpx.fit`**. Hence, in this PR I've added a new function, `fit_lbfgs`, that's a hybrid between the `fit_scipy` and `fit` functions, using Optax's LBFGS solver in a lax.while loop.
- There …
=> Add `fit_lbfgs` using Optax
