- docs/nbs/kernels.ipynb
- gpjax/config.py
- gpjax/kernels.py
- gpjax/parameters.py
- tests/test_gp.py
- tests/test_kernels.py
- tests/test_parameters.py
Adds functionality to have kernels operate on specific dimensions.
> Sliced kernels

- paper.bib
- paper.md
Here are some small typographical edits to the paper. Ref: https://github.com/openjournals/joss-reviews/issues/4455
> Edits for JOSS submission

- gpjax/kernels.py
Fix stability of Matern kernels.
> Fix stability of Matern kernels

- gpjax/__init__.py
This PR is the master PR for v0.5.1
> Bump version to v0.5.1

- examples/intro_to_gps.pct.py
Fix a few typos in the introduction doc. Change type: Documentation content changes.
> Fix typos in introduction doc.

- examples/classification.pct.py
- examples/tfp_integration.pct.py
- gpjax/gps.py
An idea of mine. Would be keen to hear your thoughts @thomaspinder.
This is closer to literature convention, of the MLL being:
- $p(y|f, \theta)$ (new), NOT, $p(y|f, \theta)p(\theta)$ (as is current), for conjugate.
And propose to overload the MLL notion with 
- $p(y|f, \theta) p(f|\theta)$ (new), NOT, $p(y|f, \theta) p(f|\theta)p(\theta)$ (as is current), for Non conjugate.
This is resolved via removed passing through `priors` in the mll arguments. This cleanly addresses the MCMC issue with log-determinants, with no additional code to maintain.
> Change MLL to probability transition kernel only.

- README.md
- examples/haiku.pct.py
- examples/kernels.pct.py
- examples/yacht.pct.py
- gpjax/gps.py
Update the JaxKern dependency.
> Update jaxkern dep

- examples/regression.pct.py
Issue Number: #184
- The plots show "two sigma" intervals correctly now.
> Rectify predictive interval in `examples/regression.pct.py`

- tests/test_kernels/test_nonstationary.py
- tests/test_kernels/test_stationary.py
- tests/test_likelihoods.py
Adds new tests for nonstationary kernels, stationary kernels and likelihoods. 
> Add tests for kernels and likelihoods

- mkdocs.yml
> Fix doc build

- docs/examples/collapsed_vi.py
- docs/examples/graph_kernels.py
- docs/examples/regression.py
- docs/examples/uncollapsed_vi.py
- docs/refs.bib
- gpjax/__init__.py
- gpjax/citation.py
- poetry.lock
- pyproject.toml
- tests/test_citations.py
This PR introduces a citation function that, given an object, returns the relevant bibtex string.
Issue Number: #217
> Add cite functionality

- gpjax/dataset.py
String literal instead of sentinel class
> Merge changes from mask-missing branch

- gpjax/__init__.py
- gpjax/objectives.py
- poetry.lock
- tests/test_objectives.py
We now have the LOOCV log predictive probability metric (as discussed in the GP4ML book).
I've been using it for some fiddly kernel optimisations, so thought Id push it in
> LOOCV objective

- gpjax/__init__.py
- pyproject.toml
> Bump version

- docs/examples/barycentres.py
- docs/examples/graph_kernels.py
- docs/examples/yacht.py
Fix the broken objective references in the docs. 
> Fix broken docs

- gpjax/__init__.py
- pyproject.toml
Bumping the version number to v0.8.2.
> Bump to v0.8.2

- docs/CODE_OF_CONDUCT.md
- [-] I've formatted the new code by running `poetry run pre-commit run --all-files --show-diff-on-failure` before committing.
- [-] I've added tests for new code.
- [-] I've added docstrings for the new code.
Inline with NumFocus' ask, I have added an explicit link to our reporting form in the CoC docs.
> Point CoC breaches to our contact form.

- gpjax/gps.py
Included missing Cholesky() flag to GPR predict
> Quick fix to stop automatic switch to CG

- gpjax/parameters.py
This PR uses `replace` to update the value of parameter inside transform. Through previous discussions, failure to do this means that transform becomes an impure function.
> Fix transform

- .github/workflows/build_docs.yml
This PR allows the build docs workflow to be triggered manually.
> Add workflow dispatch

- .github/workflows/stale_prs.yml
This PR introduces a workflow that will check and close any stale PRs.
> Add workflow

- examples/poisson.py
- examples/uncollapsed_vi.py
- [-] I've added tests for new code.
- [-] I've added docstrings for the new code.
This CR fixes the broken documentation.
> Fix broken examples

- gpjax/__init__.py
- [ NA ] I've formatted the new code by running `hatch run dev:format` before committing.
Thanks for the swift approvals!
> Bump project version to 0.9.3

- examples/classification.py
- examples/constructing_new_kernels.py
- examples/graph_kernels.py
- examples/intro_to_gps.py
- examples/intro_to_kernels.py
- examples/likelihoods_guide.py
- examples/oceanmodelling.py
This PR fixes the latex equations that were broken in our documentation.
> Fix broken latex equations

- README.md
Update the README quick example to reflect changes to objective function in GPJax 0.9.0
Issue Number: Fixes #471
> update README regression example with negative objective

- gpjax/mean_functions.py
- tests/test_fit.py
- tests/test_mean_functions.py
- tests/test_numpyro_extras.py
This PR introduces addition unit tests to cover previously uncovered lines.
> Add extra tests

- gpjax/__init__.py
> bump patch version

- examples/constructing_new_kernels.py
This PR implements few bug fixes to the `constructing_new_kernels.py` script which gives 404 error in the online documentation.
> [doc] Bugfixes in constructing new kernels documentation

- README.md
> Update Slack URL
